name: Stock Alert Bot

on:
  schedule:
    # 平日（月〜金）の18時（日本時間）に実行
    - cron: '0 9 * * 1-5'
  workflow_dispatch:  # 手動実行も可能

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas requests

     - name: Run alert script
  env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  run: |
    python notify_kairi25.py \
      --tickers tickers_jpx400.txt \
      --slack_webhook "$SLACK_WEBHOOK_URL"

