name: JPX400 -20% Kairi Alert

on:
  schedule:
      # JST18:00 = UTC09:00（平日だけ実行）
    - cron: '0 9 * * 1-5'
  workflow_dispatch: {}  # 手動実行も可

jobs:
  run-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas

      - name: Run alert script
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python notify_kairi25.py --tickers tickers_jpx400.txt --slack_webhook "$SLACK_WEBHOOK_URL"
